In [1]:
import time

In [10]:
time.time()

1740463629.349

In [13]:
from time import gmtime, strftime

In [14]:
strftime("%a, %d, %b, %Y, %H:%M:%S +0000", gmtime())


'Tue, 25, Feb, 2025, 06:09:49 +0000'

In [15]:
strftime("%m, %w, %j", gmtime())

'02, 2, 056'

In [16]:
time.CLOCK_TAI

11

In [18]:
time.CLOCK_THREAD_CPUTIME_ID

3

In [20]:
import numpy as np

In [24]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [26]:
a = np.array([[1,2,3], [2,3,4]])

In [27]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [32]:
a.shape

(2, 3)

In [39]:
a[0] = 10
a

array([[10, 10, 10],
       [ 2,  3,  4]])

In [43]:
a1 = np.array([[2,3,4,5],[4,5,8,7]])
a1

array([[2, 3, 4, 5],
       [4, 5, 8, 7]])

In [44]:
a1.shape

(2, 4)

In [45]:
a1[0] = 10
a1

array([[10, 10, 10, 10],
       [ 4,  5,  8,  7]])

In [46]:
a1[1] = 20
a1

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [47]:
a[:2]

array([[10, 10, 10],
       [ 2,  3,  4]])

In [48]:
a1[:2]

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [49]:
a1[:1]

array([[10, 10, 10, 10]])

In [50]:
a1 = a[2:]

In [54]:
a1


array([], shape=(0, 3), dtype=int32)

In [57]:
a.ndim

2

In [58]:
a1.ndim

2

In [59]:
import math
a.size == math.prod(a.shape)

True

In [61]:
np.zeros(2)

array([0., 0.])

In [62]:
np.zeros(3)

array([0., 0., 0.])

In [63]:
np.empty(2)

array([0., 0.])

In [64]:
np.empty(3)

array([0., 0., 0.])

In [66]:
np.arange(2)

array([0, 1])

In [67]:
np.arange(3)

array([0, 1, 2])

In [68]:
np.linspace(0, 10, num = 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [69]:
np.linspace(3, 90, num = 4)

array([ 3., 32., 61., 90.])

In [70]:
#Adding removing and sorting elements

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [71]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
a = np.array([1,5,7,6])
b = np.array([8,7,2,1])




In [73]:
a

array([1, 5, 7, 6])

In [74]:
b


array([8, 7, 2, 1])

In [76]:
a.ndim

1

In [77]:
b.ndim

1

In [79]:
np.concatenate((a,b))

array([1, 5, 7, 6, 8, 7, 2, 1])

In [81]:
x = np.array([[1,2],[4,5]])
y = np.array([[4,8]])


In [82]:
np.concatenate((x,y), axis = 0)

array([[1, 2],
       [4, 5],
       [4, 8]])

In [83]:
x

array([[1, 2],
       [4, 5]])

In [84]:
y

array([[4, 8]])

In [85]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [87]:
a = np.arange(10)

In [88]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
b = np.array([1,2,3,4,5,6])
b.shape

(6,)