In [2]:
# How to create an array from existing data
import numpy as np

a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr1 = a[3:5]

In [4]:
arr1

array([4, 5])

In [5]:
arr1 = a[4:8]
arr1

array([5, 6, 7, 8])

In [15]:
a1 = np.array([[1,1],[2,2]])
a2 =  np.array([[3,3],[4,4]])
a1

array([[1, 1],
       [2, 2]])

In [14]:
a2

array([[3, 3],
       [4, 4]])

In [17]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [18]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [20]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [21]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [22]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])